source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'rails', '~> 5.1.4'
gem 'puma'
gem 'kaminari'
gem 'the_role', '~> 3.5'
gem 'audited', '~> 4.5'
gem 'simple_form'
gem 'jbuilder', '~> 2.5'
gem 'telegram-bot-ruby'
gem 'redis-objects'
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'devise'
gem 'devise_invitable'
gem 'geocoder'
gem 'sidekiq'
gem 'rails_12factor'
gem 'pg', '~> 0.21'

# files
gem 'carrierwave'
gem 'carrierwave-aws'
gem 'mini_magick'

# frontend
gem 'bootstrap-sass'
gem 'jquery-rails'
gem 'gmaps4rails'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'
gem 'turbolinks', '~> 5'

# monitoring
gem "sentry-raven"

group :development, :test do
  gem 'byebug'
  gem 'capybara', '~> 2.13'
  gem 'selenium-webdriver'
end

group :test do
  gem 'cucumber-rails', require: false
  gem 'database_cleaner'
  gem 'chromedriver-helper'
  gem 'faker'
end
group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
