# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end

gem 'activeadmin'
gem 'audited', '~> 4.5'
gem 'devise'
gem 'devise_invitable'
gem 'geocoder'
gem 'jbuilder', '~> 2.5'
gem 'kaminari'
gem 'pg', '~> 0.21'
gem 'puma'
gem 'rails', '~> 5.1.4'
gem 'redis-objects'
gem 'sidekiq'
gem 'simple_form'
gem 'telegram-bot-ruby'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

# files
gem 'carrierwave'
gem 'carrierwave-aws'
gem 'mini_magick'

# frontend
gem 'bootstrap-sass'
gem 'coffee-rails', '~> 4.2'
gem 'gmaps4rails'
gem 'jquery-rails'
gem 'sass-rails', '~> 5.0'
gem 'turbolinks', '~> 5'
gem 'uglifier', '>= 1.3.0'

# monitoring
gem 'sentry-raven'

group :production, :staging do
  gem 'lograge'
  gem 'rails_12factor'
end

group :development, :test do
  gem 'pry-byebug'
end

group :test do
  gem 'capybara', '~> 2.13'
  gem 'database_cleaner'
  gem 'faker'
  gem 'launchy'
  gem 'rspec-rails'
  gem 'fabrication'
end

group :development do
  gem 'spring'
  gem 'web-console', '>= 3.3.0'
end
